# Executive Summary

Bird Conservancy of the Rockies (Bird Conservancy), in conjunction with our partners, conducted the 16th consecutive year of landbird monitoring for the Integrated Monitoring in Bird Conservation Regions (IMBCR) program.  

IMBCR is based on a spatially balanced sampling design which provides inference to avian populations at various scales, from local management units to entire states or Bird Conservation Regions, facilitating conservation at local and national levels. The nested design also provides a consistent and flexible framework for understanding and comparing the status and annual changes of bird populations with local and regional context.  

Collaboration across organizations and spatial scales increases sample sizes and improves the accuracy and precision of population estimates. Analyzing the data collectively allows us to estimate detection probabilities for species that would otherwise have insufficient numbers of detections at local scales.  

For these reasons, the IMBCR program is well-positioned to address conservation and management needs for a wide range of stakeholders, encouraging an interdisciplinary approach to bird conservation that combines monitoring, research, and management.

In 2023, the IMBCR program’s area of inference encompassed four entire states (Colorado, Montana, Utah, and Wyoming) and portions of 11 additional states (Arizona, California, Idaho, Kansas, Nebraska, Nevada, New Mexico, North Dakota, Oklahoma, Oregon, and South Dakota). We surveyed across US Forest Service (USFS) Regions 1, 2, and 4 and in portions of Region 3; all of the Badlands and Prairies Bird Conservation Region (BCR 17), and portions of nine other BCRs: Great Basin (9), Northern Rockies (10), Prairie Potholes (11), Sierra Nevada (15), Southern Rockies/Colorado Plateau (16), Shortgrass Prairie (18), Central Mixed Grass Prairie (19), Sonoran and Mojave Deserts (33), and Sierra Madre Occidental (34). 

Observers conducted 16,902 point counts within 1,513 sampling units between April 30  and July 23, 2023. They detected 201,490 individual birds representing 353 species. This report summarizes the results of the 2023 field season. 

Long-term, rigorous monitoring provides valuable information on population status and allows managers and researchers to ask additional questions. We provide a few examples demonstrating the use of IMBCR data to address specific management or conservation questions using either the annual monitoring effort we conduct each year or targeted monitoring in an overlay project.
